package mysql.erd.bbs;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * �깉 �뀒�씠釉� 紐⑤뜽 �겢�옒�뒪.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Board implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 湲� �븘�씠�뵒. */
	private Integer bid;

	/** btitle. */
	private String btitle;

	/** 蹂몃Ц. */
	private String bcontent;

	/** �궗�슜�옄 �뀒�씠釉�. */
	private Users users;

	/** 湲��벖 �떆媛�. */
	private Date modtime;

	/** 議고쉶�닔. */
	private Integer viewcount;

	/** �뙎湲��닔. */
	private Integer replycount;

	/** �뙎湲� 紐⑸줉. */
	private Set<Reply> replySet;

	/**
	 * �깮�꽦�옄.
	 */
	public Board() {
		this.replySet = new HashSet<Reply>();
	}

	/**
	 * 湲� �븘�씠�뵒�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param bid
	 *            湲� �븘�씠�뵒
	 */
	public void setBid(Integer bid) {
		this.bid = bid;
	}

	/**
	 * 湲� �븘�씠�뵒�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return 湲� �븘�씠�뵒
	 */
	public Integer getBid() {
		return this.bid;
	}

	/**
	 * btitle�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param btitle
	 *            btitle
	 */
	public void setBtitle(String btitle) {
		this.btitle = btitle;
	}

	/**
	 * btitle�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return btitle
	 */
	public String getBtitle() {
		return this.btitle;
	}

	/**
	 * 蹂몃Ц�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param bcontent
	 *            蹂몃Ц
	 */
	public void setBcontent(String bcontent) {
		this.bcontent = bcontent;
	}

	/**
	 * 蹂몃Ц�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return 蹂몃Ц
	 */
	public String getBcontent() {
		return this.bcontent;
	}

	/**
	 * �궗�슜�옄 �뀒�씠釉붿쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param users
	 *            �궗�슜�옄 �뀒�씠釉�
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * �궗�슜�옄 �뀒�씠釉붿쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �궗�슜�옄 �뀒�씠釉�
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 湲��벖 �떆媛꾩쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param modtime
	 *            湲��벖 �떆媛�
	 */
	public void setModtime(Date modtime) {
		this.modtime = modtime;
	}

	/**
	 * 湲��벖 �떆媛꾩쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return 湲��벖 �떆媛�
	 */
	public Date getModtime() {
		return this.modtime;
	}

	/**
	 * 議고쉶�닔�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param viewcount
	 *            議고쉶�닔
	 */
	public void setViewcount(Integer viewcount) {
		this.viewcount = viewcount;
	}

	/**
	 * 議고쉶�닔�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return 議고쉶�닔
	 */
	public Integer getViewcount() {
		return this.viewcount;
	}

	/**
	 * �뙎湲��닔�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param replycount
	 *            �뙎湲��닔
	 */
	public void setReplycount(Integer replycount) {
		this.replycount = replycount;
	}

	/**
	 * �뙎湲��닔�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �뙎湲��닔
	 */
	public Integer getReplycount() {
		return this.replycount;
	}

	/**
	 * �뙎湲� 紐⑸줉�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param replySet
	 *            �뙎湲� 紐⑸줉
	 */
	public void setReplySet(Set<Reply> replySet) {
		this.replySet = replySet;
	}

	/**
	 * �뙎湲�瑜� 異붽��빀�땲�떎..
	 * 
	 * @param reply
	 *            �뙎湲�
	 */
	public void addReply(Reply reply) {
		this.replySet.add(reply);
	}

	/**
	 * �뙎湲� 紐⑸줉�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �뙎湲� 紐⑸줉
	 */
	public Set<Reply> getReplySet() {
		return this.replySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bid == null) ? 0 : bid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Board other = (Board) obj;
		if (bid == null) {
			if (other.bid != null) {
				return false;
			}
		} else if (!bid.equals(other.bid)) {
			return false;
		}
		return true;
	}

}
