package mysql.erd.bbs;

import java.io.Serializable;
import java.util.Date;

/**
 * �뙎湲� 紐⑤뜽 �겢�옒�뒪.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Reply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** �뙎湲� �븘�씠�뵒. */
	private Integer rid;

	/** �뙎湲� �궡�슜. */
	private String rcontent;

	/** �벑濡� �떆媛�. */
	private Date regtime;

	/** �떟湲� �뿬遺�. */
	private Integer ismine;

	/** �궗�슜�옄 �뀒�씠釉�. */
	private Users users;

	/** �깉 �뀒�씠釉�. */
	private Board board;

	/**
	 * �깮�꽦�옄.
	 */
	public Reply() {
	}

	/**
	 * �뙎湲� �븘�씠�뵒�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param rid
	 *            �뙎湲� �븘�씠�뵒
	 */
	public void setRid(Integer rid) {
		this.rid = rid;
	}

	/**
	 * �뙎湲� �븘�씠�뵒�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �뙎湲� �븘�씠�뵒
	 */
	public Integer getRid() {
		return this.rid;
	}

	/**
	 * �뙎湲� �궡�슜�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param rcontent
	 *            �뙎湲� �궡�슜
	 */
	public void setRcontent(String rcontent) {
		this.rcontent = rcontent;
	}

	/**
	 * �뙎湲� �궡�슜�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �뙎湲� �궡�슜
	 */
	public String getRcontent() {
		return this.rcontent;
	}

	/**
	 * �벑濡� �떆媛꾩쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param regtime
	 *            �벑濡� �떆媛�
	 */
	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	/**
	 * �벑濡� �떆媛꾩쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �벑濡� �떆媛�
	 */
	public Date getRegtime() {
		return this.regtime;
	}

	/**
	 * �떟湲� �뿬遺��쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param ismine
	 *            �떟湲� �뿬遺�
	 */
	public void setIsmine(Integer ismine) {
		this.ismine = ismine;
	}

	/**
	 * �떟湲� �뿬遺��쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �떟湲� �뿬遺�
	 */
	public Integer getIsmine() {
		return this.ismine;
	}

	/**
	 * �궗�슜�옄 �뀒�씠釉붿쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param users
	 *            �궗�슜�옄 �뀒�씠釉�
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * �궗�슜�옄 �뀒�씠釉붿쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �궗�슜�옄 �뀒�씠釉�
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * �깉 �뀒�씠釉붿쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param board
	 *            �깉 �뀒�씠釉�
	 */
	public void setBoard(Board board) {
		this.board = board;
	}

	/**
	 * �깉 �뀒�씠釉붿쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �깉 �뀒�씠釉�
	 */
	public Board getBoard() {
		return this.board;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rid == null) ? 0 : rid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Reply other = (Reply) obj;
		if (rid == null) {
			if (other.rid != null) {
				return false;
			}
		} else if (!rid.equals(other.rid)) {
			return false;
		}
		return true;
	}

}
