package mysql.erd.bbs;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * �궗�슜�옄 �뀒�씠釉� 紐⑤뜽 �겢�옒�뒪.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Users implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** �궗�슜�옄 �븘�씠�뵒. */
	private String uid;

	/** �뙣�뒪�썙�뱶. */
	private String pwd;

	/** �궗�슜�옄 �씠由�. */
	private String uname;

	/** email. */
	private String email;

	/** 媛��엯�씪�옄. */
	private Date regdate;

	/** �깉 �뀒�씠釉� 紐⑸줉. */
	private Set<Board> boardSet;

	/** �뙎湲� 紐⑸줉. */
	private Set<Reply> replySet;

	/**
	 * �깮�꽦�옄.
	 */
	public Users() {
		this.boardSet = new HashSet<Board>();
		this.replySet = new HashSet<Reply>();
	}

	/**
	 * �궗�슜�옄 �븘�씠�뵒�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param uid
	 *            �궗�슜�옄 �븘�씠�뵒
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * �궗�슜�옄 �븘�씠�뵒�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �궗�슜�옄 �븘�씠�뵒
	 */
	public String getUid() {
		return this.uid;
	}

	/**
	 * �뙣�뒪�썙�뱶�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param pwd
	 *            �뙣�뒪�썙�뱶
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * �뙣�뒪�썙�뱶�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �뙣�뒪�썙�뱶
	 */
	public String getPwd() {
		return this.pwd;
	}

	/**
	 * �궗�슜�옄 �씠由꾩쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param uname
	 *            �궗�슜�옄 �씠由�
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * �궗�슜�옄 �씠由꾩쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �궗�슜�옄 �씠由�
	 */
	public String getUname() {
		return this.uname;
	}

	/**
	 * email�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * email�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * 媛��엯�씪�옄�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param regdate
	 *            媛��엯�씪�옄
	 */
	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	/**
	 * 媛��엯�씪�옄�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return 媛��엯�씪�옄
	 */
	public Date getRegdate() {
		return this.regdate;
	}

	/**
	 * �깉 �뀒�씠釉� 紐⑸줉�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param boardSet
	 *            �깉 �뀒�씠釉� 紐⑸줉
	 */
	public void setBoardSet(Set<Board> boardSet) {
		this.boardSet = boardSet;
	}

	/**
	 * �깉 �뀒�씠釉붾�� 異붽��빀�땲�떎..
	 * 
	 * @param board
	 *            �깉 �뀒�씠釉�
	 */
	public void addBoard(Board board) {
		this.boardSet.add(board);
	}

	/**
	 * �깉 �뀒�씠釉� 紐⑸줉�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �깉 �뀒�씠釉� 紐⑸줉
	 */
	public Set<Board> getBoardSet() {
		return this.boardSet;
	}

	/**
	 * �뙎湲� 紐⑸줉�쓣 �꽕�젙�빀�땲�떎..
	 * 
	 * @param replySet
	 *            �뙎湲� 紐⑸줉
	 */
	public void setReplySet(Set<Reply> replySet) {
		this.replySet = replySet;
	}

	/**
	 * �뙎湲�瑜� 異붽��빀�땲�떎..
	 * 
	 * @param reply
	 *            �뙎湲�
	 */
	public void addReply(Reply reply) {
		this.replySet.add(reply);
	}

	/**
	 * �뙎湲� 紐⑸줉�쓣 媛��졇�샃�땲�떎..
	 * 
	 * @return �뙎湲� 紐⑸줉
	 */
	public Set<Reply> getReplySet() {
		return this.replySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((uid == null) ? 0 : uid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Users other = (Users) obj;
		if (uid == null) {
			if (other.uid != null) {
				return false;
			}
		} else if (!uid.equals(other.uid)) {
			return false;
		}
		return true;
	}

}
